// The address check, which is the last thing standing between a gift code and a transfer to
// nobody.
//
// THE ADDRESSES BELOW ARE REAL ONES. `VALID_TRON` is the USDT TRC20 contract itself - a
// published address anybody can verify against a block explorer, which is the point: a test
// fixture generated by the same base58check code it is testing would agree with any bug in
// it. The typo variants are that address with ONE character changed, which is exactly the
// failure this file exists to catch.
import { describe, it, expect } from 'vitest';

import { checksumOk, readWallet, walletField } from '../src/domain/wallet.ts';

/** Tether's own TRC20 contract address. Published, checkable, and not minted by this code. */
const VALID_TRON = 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t';

/** A second real one, so nothing below can pass by accident on a single fixture. */
const VALID_TRON_2 = 'TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7';

const VALID_EVM = '0xdAC17F958D2ee523a2206206994597C13D831ec7';

/** @internal Shorthand: does the shared zod field accept this? */
function accepted(value: string): boolean {
    return walletField.safeParse(value).success;
}

describe('reading a wallet address', () => {
    it('names the network from the shape, without being told', async () => {
        // A dropdown asking "which network?" is one more thing for a buyer to get wrong, and
        // the two formats cannot be mistaken for one another anyway.
        expect(readWallet(VALID_TRON)?.network).toBe('TRC20');
        expect(readWallet(VALID_EVM)?.network).toBe('ERC20');
        await expect(checksumOk(readWallet(VALID_TRON)!)).resolves.toBe(true);
        await expect(checksumOk(readWallet(VALID_TRON_2)!)).resolves.toBe(true);
    });

    it('keeps the case exactly as it arrived', () => {
        // Base58 is case-sensitive, so a lowercased Tron address is a DIFFERENT address. And
        // an EVM address in mixed case carries an EIP-55 checksum that this file cannot
        // verify but the operator's wallet can - flattening it throws that away.
        expect(readWallet(VALID_EVM)?.address).toBe(VALID_EVM);
        expect(readWallet(`  ${VALID_TRON}  `)?.address).toBe(VALID_TRON);
    });

    it('survives the invisible characters a Persian paste carries', () => {
        // A buyer copies the address out of a Telegram message and the bidi marks come with
        // it. They render as nothing, so an address rejected because of one is an address
        // the buyer can see is correct and cannot make work.
        expect(readWallet(`\u202B${VALID_TRON}\u202C`)?.address).toBe(VALID_TRON);
        expect(readWallet(`${VALID_EVM}\u200E`)?.address).toBe(VALID_EVM);
    });

    it('refuses what is not an address at all', () => {
        for (const bad of [
            '',
            'not an address',
            // Right prefix, wrong length - 33 characters.
            'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6',
            // Base58 has no 0, O, I or l, and this uses one.
            'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjL0Ot',
            // An EVM address one nibble short.
            '0xdAC17F958D2ee523a2206206994597C13D831ec',
            // A bitcoin address: a real address, on a chain this shop does not pay out on.
            '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'
        ]) {
            expect(readWallet(bad)).toBeNull();
            expect(accepted(bad)).toBe(false);
        }
    });
});

describe('the base58check guard', () => {
    it('rejects a Tron address with ONE character wrong', async () => {
        // THE CHECK THAT EARNS ITS KEEP. Every string below has the right prefix, the right
        // length and a legal alphabet, so a shape check waves all of them through - and each
        // one is an irreversible transfer into the void.
        const typos = [
            // Last character changed.
            'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6u',
            // A character in the middle changed.
            'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLk6t',
            // Two adjacent characters transposed - the classic hand-copy slip.
            'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjjL6t'
        ];

        for (const typo of typos) {
            // Every one of them passes the shape check. That is the whole point.
            expect(readWallet(typo)?.network).toBe('TRC20');
            await expect(checksumOk(readWallet(typo)!)).resolves.toBe(false);
        }
    });

    it('passes any well-shaped EVM address, and that is a documented limit', async () => {
        // An EVM address has no checksum of its own; EIP-55 lives in the letter case and
        // needs keccak-256, which neither Web Crypto nor node:crypto implements. This test
        // exists so that limit is written down as a CLAIM rather than discovered later -
        // if it ever stops being true, this is the test that should fail.
        const wallet = readWallet('0x0000000000000000000000000000000000000000')!;
        await expect(checksumOk(wallet)).resolves.toBe(true);
    });
});
